// product
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';
export const GET_PRODUCT_LIST_FAILED = 'GET_PRODUCT_LIST_FAILED';
export const MODIFY_PRODUCT_SUCCESS = 'MODIFY_PRODUCT_SUCCESS';
export const MODIFY_PRODUCT_FAILED = 'MODIFY_PRODUCT_FAILED';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';


// auth
export const LOGIN_CHECK_SUCCESS = 'LOGIN_CHECK_SUCCESS';
export const LOGIN_CHECK_FAILED = 'LOGIN_CHECK_FAILED';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const JOIN = 'JOIN';
export const JOIN_SUCCESS = 'JOIN_SUCCESS';
export const JOIN_FAILED = 'JOIN_FAILED';

// order
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS';
export const GET_ORDER_LIST_FAILED = 'GET_ORDER_LIST_FAILED';

// notification
export const RESET = 'RESET';